# File: .github/workflows/setup-node/action.yml
name: setup-node
description: "Setup Node.js âš™ï¸ - Enable Corepack ğŸ”§ - Cache dependencies âš¡"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js and Enable Corepack âš™ï¸
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'
        corepack: true

    - name: Install Dependencies
      run: yarn install --immutable
