name: setup-node
description: "Setup Node.js âš™ï¸ - Enable Corepack ğŸ”§ - Cache dependencies âš¡"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js âš™ï¸
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'

    - name: Install Corepack ğŸ”§
      run: npm install -g corepack

    - name: Enable Corepack
      run: corepack enable

    - name: Prepare Yarn
      run: corepack prepare yarn@4.5.0 --activate

    - name: Check Yarn Version
      run: yarn --version

    - name: Install Dependencies ğŸ”§
      run: yarn install --immutable
